f= False
m= True
F= 2
M= 3
e= 4

dados= {
	'Ll': {
	'Akira Demenech': ['Uma casa amarela fica', 'O sobrado vermelho está', 'Uma gruta sem nenhum musco se localiza'],
	 'Debora Maruyama': ['um caminho escuro fica'],
	 'Luana Bibiano': ['Um prédio feito de chocolate reside'],
	 'Fábio Alcover': ['A igreja fica'],
	 'Miguel Felipe Pereira': ['O Pagode da Tia Ciça fica'],
	 'Ingrid Midori Noguti Catarino': ['A igreja está'],
	 'Isadora Vanço': ['Um lago dourado ficava'],
	 'Fernanda Martins': ['A escola continua'],
	 'Gustavo de Oliveira Martins': ['O ponto de ônibus permanece'],
	 'Camila Mossi': ['O ninho do joão-de-barro fica', 'O armário fica'],
	 'Isadora Camillo': ['O banco fica'],
	 'Sabrina Heck': ['A clínica psiquiátrica fica'],
	 'Edson Henrique Rosa Zarpellon': ['A plataforma do 210 fica'],
	 'Vizette Priscila Seidel': ['Há uma série de lacunas'],
	 'Gustavo Palote': ['O esgoto do bairro igapó fica'],
	 'Danilo Calcanhoto': ['O palácio real está'],
	 'Júlia Demenech Mori': ['O cruzamento dos tijolos amarelos está'],
	 'Lucas Malezan': ['Uma pizzaria fica']},
 'lL': {
	'Akira Demenech': ['da casa azul', 'dos correios', 'do lixeiro cheio de garrafas quebradas'],
	 'Debora Maruyama': ['do zoológico'],
	 'Luana Bibiano': ['da fábrica de dragões'],
	 'Fábio Alcover': ['do bar'],
	 'Miguel Felipe Pereira': ['da rua da Igreja do Homenzinho Verde'],
	 'Ingrid Midori Noguti Catarino': ['da lojinha'],
	 'Isadora Vanço': ['do crematório enfeitado com corais'],
	 'Fernanda Martins': ['da livraria'],
	 'Gustavo de Oliveira Martins': ['da biblioteca'],
	 'Camila Mossi': ['da árvore peluda', 'do parlamento conservador'],
	 'Isadora Camillo': ['da padaria'],
	 'Sabrina Heck': ['do cemitério'],
	 'Edson Henrique Rosa Zarpellon': ['da plataforma do 203'],
	 'Vizette Priscila Seidel': ['do tempo de pragas'],
	 'Gustavo Palote': ['da feira da lua'],
	 'Danilo Calcanhoto': ['da rua pavimentada'],
	 'Júlia Demenech Mori': ['do ginásio olímpico'],
	 'Lucas Malezan': ['de uma lanchonete']},
 'Ls': {
	'Akira Demenech': ['Nos fundos do 201', 'Nas casas geminadas', 'Em uma decrépita mansão'],
	 'Debora Maruyama': ['em águas rasas'],
	 'Luana Bibiano': ['Dentro de um túnel escuro'],
	 'Fábio Alcover': ['No bar'],
	 'Miguel Felipe Pereira': ['Na Casa de Apostas Gato Manco'],
	 'Ingrid Midori Noguti Catarino': ['Em uma velha casa'],
	 'Isadora Vanço': ['No meio do galinheiro'],
	 'Fernanda Martins': ['No fundo do poço'],
	 'Gustavo de Oliveira Martins': ['Na casa noturna'],
	 'Camila Mossi': ['No fundo da garrafa', 'No meio do agulheiro'],
	 'Isadora Camillo': ['Em uma casinha'],
	 'Sabrina Heck': ['No interior do pantanal'],
	 'Edson Henrique Rosa Zarpellon': ['Ao lado da plataforma do 210'],
	 'Gustavo Palote': ['No circo animado'],
	 'Danilo Calcanhoto': ['Em uma caverna escura'],
	 'Júlia Demenech Mori': ['Nos labirintos do quintal'],
	 'Lucas Malezan': ['Em Xique-Xique Bahia']},
 'lS': {
	'Akira Demenech': ['mora o cachorro grande', 'tem uma samambaia festeira', 'o Fulano vive'],
	 'Debora Maruyama': ['o peixe se afoga'],
	 'Luana Bibiano': ['a lagartixa se esconde'],
	 'Fábio Alcover': ['tem um vira-latas caramelo'],
	 'Miguel Felipe Pereira': ['foi onde nasceu Juventino Menceslau'],
	 'Ingrid Midori Noguti Catarino': ['vive uma assustadora senhorinha'],
	 'Isadora Vanço': ['pousa um avião'],
	 'Fernanda Martins': ['ele sofre calado'],
	 'Gustavo de Oliveira Martins': ['encontrava-se o idoso'],
	 'Camila Mossi': ['moram as lembranças nubladas', 'tem uma palha'],
	 'Isadora Camillo': ['mora o fantasma'],
	 'Sabrina Heck': ['mora o timbu de bermudinha'],
	 'Edson Henrique Rosa Zarpellon': ['tem uma moça de cabelos castanhos'],
	 'Gustavo Palote': ['tem uma ratazana fedida'],
	 'Danilo Calcanhoto': ['vive um dragão adormecido'],
	 'Júlia Demenech Mori': ['as lagartixas batalham'],
	 'Lucas Malezan': ['vive minha namorada']},
 'Lp': {
	'Akira Demenech': ['No porão do Zé', 'Em cima do muro de tijolos', 'Nas mesas da pracinha'],
	 'Debora Maruyama': ['no ônibus'],
	 'Luana Bibiano': ['No meio do zoológico'],
	 'Fábio Alcover': ['Na mesa do bar'],
	 'Miguel Felipe Pereira': ['No sótão da Vó Adelaide'],
	 'Ingrid Midori Noguti Catarino': ['Na escada da escola'],
	 'Isadora Vanço': ['No fundo do oceano'],
	 'Fernanda Martins': ['Em cada canto do quarto'],
	 'Gustavo de Oliveira Martins': ['No edifício'],
	 'Camila Mossi': ['No meio do cemitério', 'Na sala de parto'],
	 'Isadora Camillo': ['No campo de futebol'],
	 'Sabrina Heck': ['Na casa do cachorro'],
	 'Edson Henrique Rosa Zarpellon': ['Na plataforma do terminal'],
	 'Vizette Priscila Seidel': ['Em contrapartida'],
	 'Gustavo Palote': ['Na escola zumbi'],
	 'Danilo Calcanhoto': ['Nas ruínas da antiga fortaleza'],
	 'Júlia Demenech Mori': ['No ponto do ônibus espacial'],
	 'Lucas Malezan': ['Na escola']},
 'lP': {
	'Akira Demenech': ['alguém caiu', 'jogou-se cartas', 'foi ouvido um barulho'],
	 'Debora Maruyama': ['alguém chorou'],
	 'Luana Bibiano': ['animais apareceram'],
	 'Fábio Alcover': ['jogou-se truco'],
	 'Miguel Felipe Pereira': ['aconteceu uma tragédia'],
	 'Ingrid Midori Noguti Catarino': ['alguém tropeçou'],
	 'Isadora Vanço': ['jogou-se balões'],
	 'Fernanda Martins': ['ecoam cantos'],
	 'Gustavo de Oliveira Martins': ['chovia baratas'],
	 'Camila Mossi': ['alguém corria risonho', 'alguém renascia'],
	 'Isadora Camillo': ['alguém pulou'],
	 'Sabrina Heck': ['encontrou-se chinelos'],
	 'Edson Henrique Rosa Zarpellon': ['ela olhou para trás'],
	 'Vizette Priscila Seidel': ['resolveram ficar'],
	 'Gustavo Palote': ['cantaram músicas fúnebres'],
	 'Danilo Calcanhoto': ['foi ouvida uma música misteriosa'],
	 'Júlia Demenech Mori': ['ouviu-se buzinas estrondosas'],
	 'Lucas Malezan': ['alguém caiu no buraco']},
 'Sl': {
	'Akira Demenech': ['O gato mora', 'Tem uma pombinha mãe-solo', 'O medo existencial vive'],
	 'Debora Maruyama': ['a exaustão deságua'],
	 'Luana Bibiano': ['Um elefante voa'],
	 'Fábio Alcover': ['O vira-latas caramelo mora'],
	 'Miguel Felipe Pereira': ['O porteiro Claudinei trabalha'],
	 'Ingrid Midori Noguti Catarino': ['O gafanhoto pai de pet mora'],
	 'Isadora Vanço': ['O estiloso peixe palhaço de gravatas correu'],
	 'Fernanda Martins': ['O pequeno cogumelo vermelho vive'],
	 'Gustavo de Oliveira Martins': ['O motorista entrou'],
	 'Camila Mossi': ['Um hipopótamo mora', 'Tem um universo'],
	 'Isadora Camillo': ['Tem uma coluna grega'],
	 'Sabrina Heck': ['O amor eterno está marcado'],
	 'Edson Henrique Rosa Zarpellon': ['Eu fugi para entrar'],
	 'Vizette Priscila Seidel': ['O mosquito da dengue se diverte'],
	 'Gustavo Palote': ['O pão vive'],
	 'Danilo Calcanhoto': ['A rainha rouba'],
	 'Júlia Demenech Mori': ['Tigres-siberianos dormiam'],
	 'Lucas Malezan': ['Agostinho Carrara mora']},
 'sL': {
	'Akira Demenech': ['na árvore podada', 'em uma casa térrea alugada', 'na farmácia'],
	 'Debora Maruyama': ['em casa'],
	 'Luana Bibiano': ['no mercadinho da esquina'],
	 'Fábio Alcover': ['na pracinha da igreja'],
	 'Miguel Felipe Pereira': ['no condomínio Couro Murcho'],
	 'Ingrid Midori Noguti Catarino': ['em um apartamento'],
	 'Isadora Vanço': ['no restaurante japonês'],
	 'Fernanda Martins': ['embaixo do tronco caído'],
	 'Gustavo de Oliveira Martins': ['na garagem do shopping'],
	 'Camila Mossi': ['na casa hipotecada', 'em uma caixa de dominós'],
	 'Isadora Camillo': ['no meio da sala'],
	 'Sabrina Heck': ['na primeira página do livro'],
	 'Edson Henrique Rosa Zarpellon': ['no 203'],
	 'Vizette Priscila Seidel': ['no verão'],
	 'Gustavo Palote': ['na feira da lua'],
	 'Danilo Calcanhoto': ['no supermercado'],
	 'Júlia Demenech Mori': ['na avenida principal'],
	 'Lucas Malezan': ['em Alcântara']},
 'Ss': {
	'Akira Demenech': ['Uma pedra mora', 'A partitura para violoncelo vive', 'A verruga simpática se instalou'],
	 'Debora Maruyama': ['as entranhas do rato estavam'],
	 'Luana Bibiano': ['O desodorante está'],
	 'Fábio Alcover': ['O padre mora'],
	 'Miguel Felipe Pereira': ['Pablo Pardal morreu'],
	 'Ingrid Midori Noguti Catarino': ['A grande verdade absoluta mora'],
	 'Isadora Vanço': ['Um pequeno dinossauro leitor pulou'],
	 'Fernanda Martins': ['O abutre permanece'],
	 'Gustavo de Oliveira Martins': ['O pagodeiro está'],
	 'Camila Mossi': ['O diabo mora', 'A democracia morre'],
	 'Isadora Camillo': ['O gato viaja'],
	 'Sabrina Heck': ['O coração amputado está'],
	 'Edson Henrique Rosa Zarpellon': ['eu fiquei'],
	 'Vizette Priscila Seidel': ['O ornitorrinco descia a rua'],
	 'Gustavo Palote': ['O lobo idiota mora'],
	 'Danilo Calcanhoto': ['O livro encantado vive'],
	 'Júlia Demenech Mori': ['O vira-lata caramelo anda'],
	 'Lucas Malezan': ['Minha casa fica']},
 'sS': {
	'Akira Demenech': ['do corvo', 'da minhoca que não gosta de maçã', 'de um copo descartável velho'],
	 'Debora Maruyama': ['do urubu'],
	 'Luana Bibiano': ['do aluno universitário'],
	 'Fábio Alcover': ['do bêbado'],
	 'Miguel Felipe Pereira': ['do seu inimigo mortal, Clodovil Pitangueira'],
	 'Ingrid Midori Noguti Catarino': ['do macaquinho de calça jeans'],
	 'Isadora Vanço': ['do gafanhoto que lutava taekwondo'],
	 'Fernanda Martins': ['da carcaça do homem morto'],
	 'Gustavo de Oliveira Martins': ['do metaleiro'],
	 'Camila Mossi': ['de deus', 'da bancada evangélica'],
	 'Isadora Camillo': ['da girafa'],
	 'Sabrina Heck': ['do pulmão que não respira'],
	 'Edson Henrique Rosa Zarpellon': ['da moça de cabelos castanhos'],
	 'Vizette Priscila Seidel': ['do inverno'],
	 'Gustavo Palote': ['do pão'],
	 'Danilo Calcanhoto': ['da fada distraída'],
	 'Júlia Demenech Mori': ['do infame Jardiel'],
	 'Lucas Malezan': ['do meu vizinho']},
 'Sp': {
	'Akira Demenech': [('A barata',f),
		 ('Ela',f),
		 ('Beltrano',m)],
	 'Debora Maruyama': [('o urubu',m)],
	 'Luana Bibiano': [('O espelho',m)],
	 'Fábio Alcover': [('Ele não',m)],
	 'Miguel Felipe Pereira': [('Cláudio Manga Larga nunca',m)],
	 'Ingrid Midori Noguti Catarino': [('A marionete',f)],
	 'Isadora Vanço': [('Variscreido do hidrante',m)],
	 'Fernanda Martins': [('A mulher',f)],
	 'Gustavo de Oliveira Martins': [('A bailarina girando no chão',f)],
	 'Camila Mossi': [('O ex-presidente desimbroxável',m),
		 ('O pica-pau não',m)],
	 'Isadora Camillo': [('A coruja',f)],
	 'Sabrina Heck': [('Ciclano',m)],
	 'Edson Henrique Rosa Zarpellon': [('Eu',e)],
	 'Vizette Priscila Seidel': [('Ratos',M),
		 ('Os jesuítas também',M),
		 ('O orador nem sempre',m)],
	 'Gustavo Palote': [('A doutora intoxicada',f)],
	 'Danilo Calcanhoto': [('A Duquesa',f)],
	 'Júlia Demenech Mori': [('A dona Madalena',f)],
	 'Lucas Malezan': [('A barata',f)]},
 'sP': {
	'Akira Demenech': [('diz que tem 7 saias de filó', 'diz que tem 7 saias de filó', 'dizem que tem 7 saias de filó', 'dizem que tem 7 saias de filó', 'disse que tenho 7 saias de filó'),
		 ('tem 1 só', 'tem 1 só', 'têm 1 só', 'têm 1 só', 'tenho 1 só'),
		 ('da cama caiu', 'da cama caiu', 'da cama caíram', 'da cama caíram', 'da cama caí')],
	 'Debora Maruyama': [('tem sonhos', 'tem sonhos', 'têm sonhos', 'têm sonhos', 'tenho sonhos')],
	 'Luana Bibiano': [('se espatifou', 'se espatifou', 'se espatifaram', 'se espatifaram', 'me espatifei')],
	 'Fábio Alcover': [('sabe de nada', 'sabe de nada', 'sabem de nada', 'sabem de nada', 'sei de nada')],
	 'Miguel Felipe Pereira': [('pede fiado', 'pede fiado', 'pedem fiado', 'pedem fiado', 'pedi fiado')],
	 'Ingrid Midori Noguti Catarino': [('estuda para a prova', 'estuda para a prova', 'estudam para a prova', 'estudam para a prova', 'estudei para a prova')],
	 'Isadora Vanço': [('caiu', 'caiu', 'caíram', 'caíram', 'caí')],
	 'Fernanda Martins': [('contou 7 verdades e 1 mentira', 'contou 7 verdades e 1 mentira', 'contaram 7 verdades e 1 mentira', 'contaram 7 verdades e 1 mentira', 'contei 7 verdades e 1 mentira')],
	 'Gustavo de Oliveira Martins': [('vomitou', 'vomitou', 'vomitaram', 'vomitaram', 'vomitei')],
	 'Camila Mossi': [('é inelegível', 'é inelegível', 'são inelegíveis', 'são inelegíveis', 'sou inelegível'),
		 ('consegue ler nada', 'consegue ler nada', 'conseguem ler nada', 'conseguem ler nada', 'consigo ler nada')],
	 'Isadora Camillo': [('voou para além do arco-íris', 'voou para além do arco-íris', 'voaram para além do arco-íris', 'voaram para além do arco-íris', 'voei para além do arco-íris')],
	 'Sabrina Heck': [('no caderno escreveu', 'no caderno escreveu', 'no caderno escreveram', 'no caderno escreveram', 'no caderno escrevi')],
	 'Edson Henrique Rosa Zarpellon': [('desviou o olhar', 'desviou o olhar', 'desviaram o olhar', 'desviaram o olhar', 'desviei o olhar')],
	 'Vizette Priscila Seidel': [('come pipoca sentada', 'come pipoca sentado', 'comem pipoca sentadas', 'comem pipoca sentados', 'comi pipoca sentado'),
		 ('queria escravizar', 'queria escravizar', 'queriam escravizar', 'queriam escravizar', 'queria escravizar'),
		 ('faz oração', 'faz oração', 'fazem oração', 'fazem oração', 'fiz oração')],
	 'Gustavo Palote': [('afirma que a terra é plana', 'afirma que a terra é plana', 'afirmam que a terra é plana', 'afirmam que a terra é plana', 'afirmo que a terra é plana')],
	 'Danilo Calcanhoto': [('brilha no céu estrelado', 'brilha no céu estrelado', 'brilham no céu estrelado', 'brilham no céu estrelado', 'brilho no céu estrelado')],
	 'Júlia Demenech Mori': [('distribui pão quentinho pela vizinhança', 'distribui pão quentinho pela vizinhança', 'distribuem pão quentinho pela vizinhança', 'distribuem pão quentinho pela vizinhança', 'distribuo pãp quentinho pela vizinhança')],
	 'Lucas Malezan': [('quer trabalhar', 'quer trabalhar', 'querem trabalhar', 'querem trabalhar', 'quero trabalhar')]},
 'Pl': {
	'Akira Demenech': ['Alguém quebrou um vaso sanitário', 'Regaram as plantas', 'As luzes foram acesas'],
	 'Debora Maruyama': ['algo se foi'],
	 'Luana Bibiano': ['Entupiram a privada'],
	 'Fábio Alcover': ['Acenderam as luzes'],
	 'Miguel Felipe Pereira': ['Uma bomba explodiu'],
	 'Ingrid Midori Noguti Catarino': ['Cantaram alto'],
	 'Isadora Vanço': ['Queimaram laços de fita amarela'],
	 'Fernanda Martins': ['Algo estranho caiu'],
	 'Gustavo de Oliveira Martins': ['Entupiram a privada'],
	 'Camila Mossi': ['Prenderam a lua', 'Plantaram esperança'],
	 'Isadora Camillo': ['Alguém pulou'],
	 'Sabrina Heck': ['Floresceram os cactos'],
	 'Vizette Priscila Seidel': ['As esquinas se encontram'],
	 'Gustavo Palote': ['comeram bife'],
	 'Danilo Calcanhoto': ['as árvores foram derrubadas'],
	 'Júlia Demenech Mori': ['Fizeram um barraco'],
	 'Lucas Malezan': ['Renderam inocentes']},
 'pL': {
	'Akira Demenech': ['no telhado da sobrinha da Maria', 'no terreno baldio', 'nas ruínas'],
	 'Debora Maruyama': ['nos olhos do mágico'],
	 'Luana Bibiano': ['no bingo de domingo'],
	 'Fábio Alcover': ['no porão'],
	 'Miguel Felipe Pereira': ['na praça João Figueira'],
	 'Ingrid Midori Noguti Catarino': ['na sala de artes'],
	 'Isadora Vanço': ['na exposição de café'],
	 'Fernanda Martins': ['no teto'],
	 'Gustavo de Oliveira Martins': ['no casamento'],
	 'Camila Mossi': ['debaixo da cama da Celeste', 'nas ruínas da guerra'],
	 'Isadora Camillo': ['no telhado destelhado'],
	 'Sabrina Heck': ['no deserto molhado'],
	 'Vizette Priscila Seidel': ['na Jk'],
	 'Gustavo Palote': ['na galáxia vegana'],
	 'Danilo Calcanhoto': ['no cemitério'],
	 'Júlia Demenech Mori': ['na quitanda do seu Fruta'],
	 'Lucas Malezan': ['no hospital']},
 'Ps': {
	'Akira Demenech': [('Está alegre', 'Está alegre', 'Estão alegres', 'Estão alegres'),
		 ('Sempre em movimento está', 'Sempre em movimento está', 'Sempre em movimento estão', 'Sempre em movimento estão'),
		 ('Bem alto gritou', 'Bem alto gritou', 'Bem alto gritaram', 'Bem alto gritaram')],
	 'Debora Maruyama': [('cantou em voz alta', 'cantou em voz alta', 'cantaram em voz alta', 'cantaram em voz alta')],
	 'Luana Bibiano': [('Sorridente anda', 'Sorridente anda', 'Sorridente andam', 'Sorridente andam')],
	 'Fábio Alcover': [('Dançou de felicidade', 'Dançou de felicidade', 'Dançaram de felicidade', 'Dançaram de felicidade')],
	 'Miguel Felipe Pereira': [('É muito feia', 'É muito feio', 'São muito feias', 'Sâo muito feios')],
	 'Ingrid Midori Noguti Catarino': [('Está muito triste', 'Está muito triste', 'Estão muito tristes', 'Estão muito tristes')],
	 'Isadora Vanço': [('Cochichou à abelha', 'Cochichou à abelha', 'Cochicharam à abelha', 'Cochicharam à abelha')],
	 'Fernanda Martins': [('Vive triste', 'Vive triste', 'Vivem tristes', 'Vivem tristes')],
	 'Gustavo de Oliveira Martins': [('A passos de tartaruga andou', 'A passos de tartaruga andou', 'A passos de tartaruga andaram', 'A passos de tartaruga andaram')],
	 'Camila Mossi': [('Estranhamente estática está', 'Estranhamente estático está', 'Estranhamente estáticas estão', 'Estranhamente estáticos estão'),
		 ('Está atrasada', 'Está atrasado', 'Estão atrasadas', 'Estão atrasados')],
	 'Isadora Camillo': [('Gritou de alegria', 'Gritou de alegria', 'Gritaram de alegria', 'Gritaram de alegria')],
	 'Sabrina Heck': [('Leu o livro obrigada', 'Leu o livro obrigado', 'Leram o livro obrigadas', 'Leram o livro obrigados')],
	 'Gustavo Palote': [('Lacrou com força', 'Lacrou com força', 'Lacraram com força', 'Lacraram com força')],
	 'Danilo Calcanhoto': [('Clamou um feitiço alegre', 'Clamou um feitiço alegre', 'Clamaram um feitiço alegre', 'Clamaram um feitiço alegre')],
	 'Júlia Demenech Mori': [('Circulou pelo bosque artificial', 'Circulou pelo bosque artificial', 'Circularam pelo bosque artificial', 'Circularam pelo bosque artificial')],
	 'Lucas Malezan': [('Desgraçada é', 'Desgraçado é', 'Desgraçadas são', 'Desgraçados são')]},
 'pS': {
	'Akira Demenech': [('a galinha-d’angola',f),
		 ('o futuro',m),
		 ('o Ciclano',m)],
	 'Debora Maruyama': [('o hino do supermercado',m)],
	 'Luana Bibiano': [('o gatinho da esquina',m)],
	 'Fábio Alcover': [('o coroinha',m)],
	 'Miguel Felipe Pereira': [('o secretário Carvalho',m)],
	 'Ingrid Midori Noguti Catarino': [('a joaninha',f)],
	 'Isadora Vanço': [('o Zé da Moela',m)],
	 'Fernanda Martins': [('o pobre homem',m)],
	 'Gustavo de Oliveira Martins': [('o médico',m)],
	 'Camila Mossi': [('a estátua',f),
		 ('o tal meteoro',m)],
	 'Isadora Camillo': [('as crianças',F)],
	 'Sabrina Heck': [('o menino da casa 779',m)],
	 'Gustavo Palote': [('a cientista futurista',f)],
	 'Danilo Calcanhoto': [('as bruxas',F)],
	 'Júlia Demenech Mori': [('a bióloga Pereira',f)],
	 'Lucas Malezan': [('a barata Gregor Samsa',f)]},
 'Pp': {
	'Akira Demenech': ['Abasteceram o caminhão do João', 'Um computador HP foi formatado', 'Queimou o churrasco'],
	 'Debora Maruyama': ['incendiaram o mapa'],
	 'Luana Bibiano': ['O quadro foi pintado'],
	 'Fábio Alcover': ['Comeram todas as óstias'],
	 'Miguel Felipe Pereira': ['Houve uma confusão'],
	 'Ingrid Midori Noguti Catarino': ['Escaparam do furto'],
	 'Isadora Vanço': ['Regaram o pé de goiaba'],
	 'Fernanda Martins': ['Falavam mal sobre ela'],
	 'Gustavo de Oliveira Martins': ['A música foi tocada'],
	 'Camila Mossi': ['Apagaram a democracia', 'Cancelaram CPFs'],
	 'Isadora Camillo': ['A corrida aconteceu'],
	 'Sabrina Heck': ['Encheram a garrafa da Mirelle'],
	 'Gustavo Palote': ['Deram um grito'],
	 'Danilo Calcanhoto': ['Arrancaram a flecha do cervo'],
	 'Júlia Demenech Mori': ['Um desfile carnavalesco festejava'],
	 'Lucas Malezan': ['A menina apertava o passo']},
 'pP': {
	'Akira Demenech': ['de onde alguém pulava corda', 'de onde mudou-se a senha do wi-fi', 'do pão de alho chorando pela separação'],
	 'Debora Maruyama': ['de onde perdeu-se o tesouro'],
	 'Luana Bibiano': ['de uma pessoa que caiu no chão'],
	 'Fábio Alcover': ['de onde se guarda o vinho'],
	 'Miguel Felipe Pereira': ['de onde a bomba explodiu'],
	 'Ingrid Midori Noguti Catarino': ['de onde se incendiou a estufa'],
	 'Isadora Vanço': ['de onde tiraram lágrimas de um boto'],
	 'Fernanda Martins': ['de onde ela se sentou'],
	 'Gustavo de Oliveira Martins': ['de onde alguém afinou o violão'],
	 'Camila Mossi': ['de onde discursam os deputados', 'do carregamento de vacinas vencendo'],
	 'Isadora Camillo': ['de onde os alunos tinham aula'],
	 'Sabrina Heck': ['de onde jogavam bola'],
	 'Gustavo Palote': ['de onde amassavam um pão'],
	 'Danilo Calcanhoto': ['de onde alguém pulava corda'],
	 'Júlia Demenech Mori': ['de uma fúnebre cerimônia'],
	 'Lucas Malezan': ['de uma figura suspeita que fugia da menina']}}
